development:
  adapter: postgresql
  encoding: unicode
  database: pocfly_dev
  pool: 5
  username: root
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: pocfly_prod
  pool: 5
  username: root
  password:

