<% user =  ENV["POSTGRESQL_USER"] %>
<% password = ENV["POSTGRESQL_PASSWORD"] %>
<% host = ENV["POSTGRESQL_HOST"]
<% port = ENV["POSTGRESQL_PORT"]
<% db_service = ENV.fetch("DATABASE_SERVICE_NAME","").upcase %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= user %>
  password: <%= password %>
  host: <%= host %>
  port: <%= port %>
  database: <%= ENV["POSTGRESQL_DATABASE"] %>

test:
  <<: *default

production:
  <<: *default
