development:
  adapter: mysql2
  encoding: utf8
  database: pocfly_dev
  username: root
  password: Prodevans@123
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: pocfly_prod
  username: root
  password: Prodevans@123
  host: 127.0.0.1
  port: 3306

