development:
  adapter: postgresql
  encoding: unicode
  database: pocfly_dev
  pool: 5
  username: root
  password: Redhat@123

test:
  adapter: postgresql
  encoding: unicode
  database: pocfly_test
  pool: 5
  username: root
  password: Redhat@123

production:
  adapter: postgresql
  encoding: unicode
  database: pocfly_prod
  pool: 5
  username: root
  password: Redhat@123

